### ISSUE TITLE
cannot install it on plone 4.1.4

### ISSUE THREAD

**Issue by yurj** [simplesconsultoria/beyondskins.responsive#1]
here the problem:

Getting distribution for 'beyondskins.responsive'.
Running easy_install:
/home/yurj/progetti/plone/plone4.1/Python-2.6/bin/python "-c" "from setuptools.command.easy_install import main; main()" "-mUNxd" "/home/yurj/progetti/plone/plone4.1/zeocluster/../buildout-cache/eggs/tmpvYSm_G" "-Z" "-q" "/home/yurj/progetti/plone/plone4.1/buildout-cache/downloads/dist/beyondskins.responsive-0.2.tar.gz"
path=/home/yurj/progetti/plone/plone4.1/buildout-cache/eggs/distribute-0.6.24-py2.6.egg

error: README.rst: No such file or directory
An error occured when trying to install beyondskins.responsive 0.2. Look above this message for any errors that were output by easy_install.
While:
  Installing client1.
#   Getting distribution for 'beyondskins.responsive'.

the egg on pypi miss the README.rst

**Comment by ericof** [comment]
Fix commited, now let's release it

**Comment by ericof** [comment]
New release fix it
